agents:
  queue: central
  slurm_mem: 8G
  modules: climacommon/2024_10_10

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "init"
    command:
      - echo "--- Instantiate the GPU test environment"
      - "julia --project=test/gpu -e 'using Pkg; Pkg.develop(; path = \".\"); Pkg.instantiate(); Pkg.precompile(); Pkg.status()'"
      - "julia --project=test/gpu -e 'using CUDA; CUDA.precompile_runtime(); CUDA.versioninfo()'"
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  # Test for kernel-safety by direct GPU compilation
  - label: "GPU kernel safety"
    key: "gpu_kernel_safety"
    command: "julia --color=yes --project=test/gpu test/gpu/kernels.jl"
    agents:
      slurm_gpus: 1
