name: CodeCov
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  merge_group:

jobs:
  test:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.11
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          test_args: 'fast_mode' # Testing with code coverage is very slow.
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          file: lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
